#lexer
#keyword print
#keyword let
#symbol SEMI ;
#symbol ASSIGN =
identifier = letter, { letter } ;

number = digit, { digit } ;

letter = "a" | "b" | "c" | "d" | "e" ;

digit = "0" | "1" | "2" | "3" | "4" ;

#parser
program = { stmt, ";" } ;

stmt = "let", identifier, "=", number | "print", identifier ;
