program
  = stmt, { ";", stmt }, [ ";" ] ;

stmt
  = "let", identifier, "=", number
  | "print", identifier ;

identifier
  = letter, { letter } ;

number
  = digit, { digit } ;

letter
  = "a" | "b" | "c" | "d" | "e" ;

digit
  = "0" | "1" | "2" | "3" | "4" ;
